In [1]:
#import library yang akan digunakan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#import dataset yang akan digunakan
dataset = pd.read_csv('travelinsurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 5].values

In [3]:
#untuk menampilkan 5data paling atas pada dataset
dataset.head()

Agency Type Destination  Net Sales  Commision (in value)  Age Claim
0  Travel Agency    MALAYSIA      -29.0                  9.57   81    No
1  Travel Agency         NaN      -29.0                  9.57   71    No
2  Travel Agency   AUSTRALIA      -49.5                 29.70   32    No
3  Travel Agency         NaN      -39.6                 23.76   32    No
4  Travel Agency       ITALY      -19.8                 11.88   41    No

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

print(X)

[['Travel Agency' 'MALAYSIA' -29.0 9.57 81]
 ['Travel Agency' nan -29.0 9.57 71]
 ['Travel Agency' 'AUSTRALIA' -49.5 29.7 32]
 ...
 ['Airlines' 'MALAYSIA' 18.0 6.3 57]
 ['Airlines' 'VIET NAM' 18.0 6.3 63]
 ['Airlines' 'HONG KONG' 26.0 9.1 35]]


In [5]:
print(y)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [6]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent') #mengisi kekosongan cell dengan method mostfreq 
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [7]:
print(X)

[['Travel Agency' 'MALAYSIA' -29.0 9.57 81]
 ['Travel Agency' 'SINGAPORE' -29.0 9.57 71]
 ['Travel Agency' 'AUSTRALIA' -49.5 29.7 32]
 ...
 ['Airlines' 'MALAYSIA' 18.0 6.3 57]
 ['Airlines' 'VIET NAM' 18.0 6.3 63]
 ['Airlines' 'HONG KONG' 26.0 9.1 35]]


In [8]:
print(y)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[0.0 1.0 'MALAYSIA' -29.0 9.57 81]
 [0.0 1.0 'SINGAPORE' -29.0 9.57 71]
 [0.0 1.0 'AUSTRALIA' -49.5 29.7 32]
 ...
 [1.0 0.0 'MALAYSIA' 18.0 6.3 57]
 [1.0 0.0 'VIET NAM' 18.0 6.3 63]
 [1.0 0.0 'HONG KONG' 26.0 9.1 35]]


In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
print(y)

[0 0 0 ... 0 0 0]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [14]:
print(X_train)

[[0.0 1.0 'HONG KONG' 28.0 0.0 36]
 [1.0 0.0 'INDIA' 31.0 12.4 118]
 [0.0 1.0 'CHINA' 27.0 0.0 36]
 ...
 [0.0 1.0 'INDONESIA' 10.0 0.0 24]
 [0.0 1.0 'INDONESIA' 20.0 0.0 36]
 [1.0 0.0 'MALAYSIA' 30.0 10.5 56]]


In [15]:
print(X_test)

[[0.0 1.0 'KOREA, REPUBLIC OF' 0.0 0.0 36]
 [0.0 1.0 'MALAYSIA' 10.0 0.0 41]
 [1.0 0.0 'BRUNEI DARUSSALAM' 23.0 9.2 39]
 ...
 [1.0 0.0 'MYANMAR' 47.0 16.45 35]
 [0.0 1.0 'SINGAPORE' 10.0 0.0 26]
 [0.0 1.0 'CHINA' 26.0 0.0 36]]


In [16]:
print(y_train)

[0 0 0 ... 0 0 0]


In [17]:
print(y_test)

[0 0 0 ... 0 0 0]


In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [19]:
print(X_train)

[[0.0 1.0 'HONG KONG' -0.25881633042200636 -0.4949834601311455
  -0.28503129922641834]
 [1.0 0.0 'INDIA' -0.19730665610453219 0.13009796153692338
  5.540201137284157]
 [0.0 1.0 'CHINA' -0.27931955519449775 -0.4949834601311455
  -0.28503129922641834]
 ...
 [0.0 1.0 'INDONESIA' -0.6278743763268513 -0.4949834601311455
  -1.1375043387157708]
 [0.0 1.0 'INDONESIA' -0.42284212860193743 -0.4949834601311455
  -0.28503129922641834]
 [1.0 0.0 'MALAYSIA' -0.21780988087702358 0.0343193566039128
  1.1357570999225026]]


In [20]:
print(X_test)

[[0.0 1.0 'KOREA, REPUBLIC OF' -0.8329066240517651 -0.4949834601311455
  -0.28503129922641834]
 [0.0 1.0 'MALAYSIA' -0.6278743763268513 -0.4949834601311455
  0.07016580056081187]
 [1.0 0.0 'BRUNEI DARUSSALAM' -0.36133245428446326 -0.03121337308709446
  -0.07191303935408022]
 ...
 [1.0 0.0 'MYANMAR' 0.13074494025532996 0.3342576194204458
  -0.3560707191838644]
 [0.0 1.0 'SINGAPORE' -0.6278743763268513 -0.4949834601311455
  -0.9954254988008788]
 [0.0 1.0 'CHINA' -0.2998227799669891 -0.4949834601311455
  -0.28503129922641834]]
